#!/bin/bash

### color code ###
BLACK="30m"
RED="31m"
GREEN="32m"
YELLOW="33m"
BLUE="34m"
MAGENTA="35m"
CYAN="36m"
WHITE="37m"

LIGHT_BLACK="1;30m"
LIGHT_RED="1;31m"
LIGHT_GREEN="1;32m"
LIGHT_YELLOW="1;33m"
LIGHT_BLUE="1;34m"
LIGHT_MAGENTA="1;35m"
LIGHT_CYAN="1;36m"
LIGHT_WHITE="1;37m"

###
colored(){
  echo -e "\033[${1}${@:2}\033[0m" 1>& 2
}

### main ###

echo
colored ${CYAN} "Query IP behind a socks5 proxy..."

#Check for ``curl``` package
if ! command -v curl > /dev/null; then
  echo
  echo
  colored ${LIGHT_YELLOW} "Need ``curl`` package"
  colored ${LIGHT_BLACK} ">>> sudo apt install curl -y"
  echo
  sudo apt install curl -y
  echo
  echo
fi

# exec
colored ${LIGHT_BLACK} ">>> curl https://api.myip.com/ --socks5 $*"
echo
curl https://api.myip.com/ --socks5 $*
echo
echo
